"use strict";
exports.__esModule = true;
exports.MAX_MAIN_BOX_MSG_SIZE = exports.MAX_USER_BOX_MSG_SIZE = exports.USER_NOOP_TXNS = exports.CHANNEL_NOOP_TXNS = exports.ACC_ARG_NULL = exports.APP_ARG_NULL = exports.APP_ARG_CHANNEL_CREATE = exports.GLOBAL_BYTES = exports.LOCAL_BYTES = exports.GLOBAL_INTS = exports.LOCAL_INTS = exports.APP_ARG_PVT = exports.APP_ARG_PUB = exports.ZERO_TXN = exports.NOTIBOY_APP_INDEX = exports.SC_ESCHROW = exports.DAPP_ESCROW = exports.NOTIBOY_BOX_NAME = exports.ASA_ASSET = exports.USER_BOX_CREATION_FEE = exports.CHANNEL_CREATION_FEE = void 0;
//Constants for the sdk
exports.CHANNEL_CREATION_FEE = 25000000;
exports.USER_BOX_CREATION_FEE = 5000000;
exports.ASA_ASSET = 10458941;
exports.NOTIBOY_BOX_NAME = "notiboy";
exports.DAPP_ESCROW = "PMJ44TV52KSPIP6RMTPCEPXTFWKGCNQ2YDTYXQYDXU2OG7CMHZXEAN4W2E";
exports.SC_ESCHROW = "4LAT7PGGPCCF7MIZVV5BUGX3GCEQZHNDA7BIBXYO3G7PJBR6R2AAW5TSVI";
exports.NOTIBOY_APP_INDEX = 151255921;
exports.ZERO_TXN = 0;
exports.APP_ARG_PUB = "pub_notify";
exports.APP_ARG_PVT = "pvt_notify";
exports.LOCAL_INTS = 0;
exports.GLOBAL_INTS = 0;
exports.LOCAL_BYTES = 16;
exports.GLOBAL_BYTES = 64;
exports.APP_ARG_CHANNEL_CREATE = [];
exports.APP_ARG_NULL = [];
exports.ACC_ARG_NULL = [];
exports.CHANNEL_NOOP_TXNS = 4;
exports.USER_NOOP_TXNS = 1;
exports.MAX_USER_BOX_MSG_SIZE = 296;
exports.MAX_MAIN_BOX_MSG_SIZE = 19;
